### ISSUE TITLE
插件在linux服务器上运行时无法加载，报错

### ISSUE THREAD

**Issue by kukemc** [TheRamU/ServerShout#2]
服务端: velocity-3.4.0
系统: linux
插件版本: 2.1.2
问题描述: 在加载插件时，插件报出了以下错误:

[19:17:17 INFO] [servershout]: 
[19:17:17 INFO] [servershout]:  ServerShout v2.1.2 by TheRamU
[19:17:17 INFO] [servershout]: 
[19:17:17 INFO] [servershout]: Loading configuration...
[19:17:17 INFO] [servershout]: Loading plugin configuration...
[19:17:17 ERROR]: Couldn't pass ProxyInitializeEvent to servershout 2.1.2
java.io.FileNotFoundException: ./plugins/ServerShout/config.yml (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
        at io.github.theramu.servershout.common.config.YamlConfig.<init>(YamlConfig.kt:17) ~[?:?]
        at io.github.theramu.servershout.common.config.ConfigLoader.getVerifiedConfig(ConfigLoader.kt:61) ~[?:?]
        at io.github.theramu.servershout.common.config.ConfigLoader.loadConfig(ConfigLoader.kt:43) ~[?:?]
        at io.github.theramu.servershout.common.ServerShoutApi.load(ServerShoutApi.kt:45) ~[?:?]
        at io.github.theramu.servershout.common.ServerShoutProxyApi.load(ServerShoutProxyApi.kt:14) ~[?:?]
        at io.github.theramu.servershout.common.ServerShoutApi.onEnable(ServerShoutApi.kt:35) ~[?:?]
        at io.github.theramu.servershout.velocity.ServerShoutVelocityApi.onEnable(ServerShoutVelocityApi.kt:33) ~[?:?]
        at io.github.theramu.servershout.velocity.ServerShoutVelocityPlugin.onProxyInitialization(ServerShoutVelocityPlugin.java:76) ~[?:?]
        at io.github.theramu.servershout.velocity.Lmbda$29.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[BungeeCord.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[BungeeCord.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[BungeeCord.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?]

具体原因推测: 应该是插件创建出来的文件夹名称为"servershout"均为小写，而插件加载配置文件的路径为"ServerShout"
在 linux 上对文件名的大小写是敏感的，而 Windows 则不敏感，刚才也测试了在 win 环境下跑没毛病
（本人非专业 只是推测 可能有误）

**Comment by kukemc** [comment]
临时解决办法：把文件夹手动改成大写就好了
